// web/src/pages/accounts/TasksModal.tsx
// 单个账号的积分任务：查询上游任务进度；「接受」为报名（幂等），「领取」在进度达标后可用，
// 可自动完成的任务给「一键完成」。所有操作走网关，无需外部脚本。
import { useState } from 'react'
import { Alert, Button, Chip, CloseButton, Modal, Table, toast, useMediaQuery } from '@heroui/react'
import { useQueryClient } from '@tanstack/react-query'
import { acct, post } from '../../lib/api'
import { toastError } from '../../lib/hooks'
import { qk, useTasks } from '../../lib/queries'
import { AUTO_TASKS } from '../../lib/tasks'
import type { AcceptAllResp, AutoAllItem, AutoResult, Task } from '../../lib/types'
import { BusyButton, Empty, Loaded } from '../../components/Feedback'
import { useConfirm } from '../../components/useConfirm'

export function TasksModal({ uid, name, onClose }: { uid: string | null; name: string; onClose: () => void }) {
  const isDesktop = useMediaQuery('(min-width: 768px)')
  return (
    <Modal.Backdrop isOpen={!!uid} onOpenChange={(v) => { if (!v) onClose() }}>
      <Modal.Container size={isDesktop ? 'lg' : 'full'} scroll="inside">
        <Modal.Dialog className={isDesktop ? 'sm:max-w-5xl' : undefined}>
          <Modal.CloseTrigger />
          <Modal.Header>
            <Modal.Heading>积分任务 <span className="text-sm font-normal text-muted">{name}</span></Modal.Heading>
            <p className="mt-1.5 text-sm text-muted">「接受」为报名（幂等），「领取」在进度达标后可用。所有操作走网关，无需外部脚本。</p>
          </Modal.Header>
          {uid && <TasksBody key={uid} uid={uid} wide={isDesktop} onClose={onClose} />}
        </Modal.Dialog>
      </Modal.Container>
    </Modal.Backdrop>
  )
}

function badge(t: Task) {
  if (t.claimed) return <Chip size="sm" variant="soft" color="success">已领取</Chip>
  if (t.claimable) return <Chip size="sm" variant="soft" color="warning">可领取</Chip>
  if (t.locked) return <Chip size="sm" variant="soft">未解锁</Chip>
  if (t.accept_status === 'accepted') return <Chip size="sm" variant="soft">进行中</Chip>
  return <Chip size="sm" variant="soft">未接受</Chip>
}

const progress = (t: Task) => {
  const cur = t.current ?? 0, tgt = t.target ?? 0
  return tgt ? cur + ' / ' + tgt : cur > 0 ? String(cur) : '—'
}

const reward = (t: Task) => {
  const parts = []
  if (t.credit) parts.push('+' + t.credit + ' 分')
  if (t.energy) parts.push('+' + t.energy + ' 能')
  if (t.reward_buddy) parts.push('Buddy')
  return parts.join(' ') || '—'
}

function TasksBody({ uid, wide, onClose }: { uid: string; wide: boolean; onClose: () => void }) {
  const qc = useQueryClient()
  const query = useTasks(uid)
  const [busy, setBusy] = useState<string | null>(null)
  const [autoAll, setAutoAll] = useState<AutoAllItem[] | null>(null)
  const [confirmEl, ask] = useConfirm()
  const reload = () => void qc.invalidateQueries({ queryKey: qk.tasks(uid) })

  const act = async (kind: 'accept' | 'claim' | 'auto', code: string) => {
    setBusy(kind + ':' + code)
    try {
      if (kind === 'auto') {
        // 一键完成：后端执行动作 → 回读进度 → 汇报（耗时可到分钟级，含真实对话）
        const r = await post<AutoResult>(acct(uid, 'tasks/auto'), { task_code: code })
        if (r.skipped) {
          toast.success(r.message || '已跳过')
        } else {
          const advanced = r.progress_before !== r.progress_after
          let msg = r.message || '已执行'
          if (r.progress_after) msg += `（进度 ${r.progress_before} → ${r.progress_after}）`
          if (r.claimed) msg += '，奖励已自动到账'
          else if (r.claimable) msg += r.claim_error ? '，可点「领取」重试' : ''
          else if (r.attempt && !advanced) msg += '；进度未动，该任务可能需要官方客户端'
          if (r.claimed || advanced) toast.success(msg)
          else toast.danger(msg)
        }
        void qc.invalidateQueries({ queryKey: qk.overview })
      } else if (kind === 'claim') {
        await post(acct(uid, 'tasks/claim'), { task_code: code })
        toast.success('已领取奖励')
        void qc.invalidateQueries({ queryKey: qk.overview })
      } else {
        await post(acct(uid, 'tasks/accept'), { task_codes: [code] })
        toast.success('已接受任务')
      }
    } catch (e) {
      toastError(e)
    } finally {
      setBusy(null)
      reload()
    }
  }

  const acceptAll = async () => {
    setBusy('accept_all')
    try {
      const r = await post<AcceptAllResp>(acct(uid, 'tasks/accept_all'))
      const n = r.accepted || 0
      if (r.failed?.length) toast.danger(`已接受 ${n} 个，${r.failed.length} 个被上游拒绝（可重试）`, { description: r.failed.join('、') })
      else toast.success(n ? `已接受 ${n} 个任务` : r.message || '所有任务均已接受')
    } catch (e) {
      toastError(e)
    } finally {
      setBusy(null)
      reload()
    }
  }

  const runAutoAll = async () => {
    setBusy('auto_all')
    setAutoAll(null)
    try {
      const r = await post<{ results: AutoAllItem[] | null }>(acct(uid, 'tasks/auto_all'))
      setAutoAll(r.results || [])
      void qc.invalidateQueries({ queryKey: qk.overview })
    } catch (e) {
      toastError(e)
    } finally {
      setBusy(null)
      reload()
    }
  }

  const actionFor = (t: Task) => {
    if (t.claimed || t.locked) return null
    const b = (kind: 'accept' | 'claim' | 'auto', label: string, variant: 'primary' | 'secondary') => (
      <BusyButton size="sm" variant={variant} busy={busy === kind + ':' + t.task_code} isDisabled={!!busy && busy !== kind + ':' + t.task_code}
        onPress={() => void act(kind, t.task_code)}>{label}</BusyButton>
    )
    if (t.claimable) return b('claim', '领取', 'primary')
    if (AUTO_TASKS[t.task_code]) return b('auto', '一键完成', 'primary')
    if (t.accept_status === 'accepted') return null
    return b('accept', '接受', 'secondary')
  }

  return (
    <>
      <Modal.Body className="flex flex-col gap-4">
        {autoAll && <AutoAllResult items={autoAll} onDismiss={() => setAutoAll(null)} />}
        <Loaded query={query} rows={6}>
          {(d) => {
            // 有进度或可领取的排前面，已领取沉底——一眼看到「现在该做什么」
            const list = [...(d.tasks || [])].sort((a, b) =>
              Number(!!a.claimed) - Number(!!b.claimed) || Number(!!b.claimable) - Number(!!a.claimable) ||
              String(a.task_code).localeCompare(String(b.task_code)))
            if (!list.length) return <Empty title="该账号暂无任务" />
            const guide = (t: Task) => [t.task_desc || t.description, AUTO_TASKS[t.task_code] && '可自动：' + AUTO_TASKS[t.task_code], t.jump_url && '跳转：' + t.jump_url].filter(Boolean).join('\n')
            if (!wide) {
              return (
                <ul className="flex flex-col divide-y divide-separator">
                  {list.map((t) => (
                    <li key={t.task_code} className="flex flex-col gap-1.5 py-3">
                      <div className="flex items-start justify-between gap-2">
                        <span className="font-medium">{t.title || t.task_code}</span>
                        {badge(t)}
                      </div>
                      <span className="font-mono text-xs text-muted">{t.task_code}{t.tag ? ' · ' + t.tag : ''}</span>
                      {guide(t) && <p className="whitespace-pre-line text-xs text-muted">{guide(t)}</p>}
                      <div className="flex items-center justify-between gap-2 text-sm">
                        <span className="tabular-nums text-muted">进度 {progress(t)} · {reward(t)}</span>
                        {actionFor(t)}
                      </div>
                    </li>
                  ))}
                </ul>
              )
            }
            return (
              <Table variant="secondary">
                <Table.ScrollContainer>
                  <Table.Content aria-label="积分任务">
                    <Table.Header>
                      <Table.Column isRowHeader>任务</Table.Column>
                      <Table.Column>进度</Table.Column>
                      <Table.Column>奖励</Table.Column>
                      <Table.Column>状态</Table.Column>
                      <Table.Column className="w-0"> </Table.Column>
                    </Table.Header>
                    <Table.Body>
                      {list.map((t) => (
                        <Table.Row key={t.task_code} id={t.task_code}>
                          <Table.Cell>
                            <div className="flex max-w-md flex-col gap-0.5">
                              <span className="font-medium">{t.title || t.task_code}</span>
                              <span className="font-mono text-xs text-muted">{t.task_code}{t.tag ? ' · ' + t.tag : ''}</span>
                              {guide(t) && <span className="line-clamp-3 whitespace-pre-line text-xs text-muted" title={guide(t)}>{guide(t)}</span>}
                            </div>
                          </Table.Cell>
                          <Table.Cell className="whitespace-nowrap tabular-nums">{progress(t)}</Table.Cell>
                          <Table.Cell className="whitespace-nowrap">{reward(t)}</Table.Cell>
                          <Table.Cell>{badge(t)}</Table.Cell>
                          <Table.Cell>{actionFor(t)}</Table.Cell>
                        </Table.Row>
                      ))}
                    </Table.Body>
                  </Table.Content>
                </Table.ScrollContainer>
              </Table>
            )
          }}
        </Loaded>
      </Modal.Body>
      <Modal.Footer className="flex-wrap">
        <Button variant="tertiary" onPress={onClose}>关闭</Button>
        <Button variant="secondary" isDisabled={!!busy} onPress={reload}>重新查询</Button>
        <BusyButton variant="secondary" busy={busy === 'accept_all'} isDisabled={!!busy && busy !== 'accept_all'} onPress={() => void acceptAll()}>全部接受</BusyButton>
        <BusyButton
          variant="primary"
          busy={busy === 'auto_all'}
          isDisabled={!!busy && busy !== 'auto_all'}
          onPress={() => ask({
            title: '一键完成可自动任务？',
            body: '将依次执行：补报对话事件、领取 Buddy、glm-5.2 对话、尝试上报。过程约 1–2 分钟（含真实对话）。',
            confirmLabel: '开始执行',
            danger: false,
            onConfirm: () => void runAutoAll(),
          })}
        >
          {busy === 'auto_all' ? '执行中…' : '一键完成可自动任务'}
        </BusyButton>
      </Modal.Footer>
      {confirmEl}
    </>
  )
}

const STATUS: Record<string, { label: string; color: 'success' | 'danger' | 'default' }> = {
  done: { label: '完成', color: 'success' },
  error: { label: '失败', color: 'danger' },
  skipped: { label: '跳过', color: 'default' },
}

/** 「一键完成可自动任务」的逐项结果（原先只打印在浏览器控制台） */
function AutoAllResult({ items, onDismiss }: { items: AutoAllItem[]; onDismiss: () => void }) {
  const n = (s: string) => items.filter((x) => x.status === s).length
  const err = n('error')
  return (
    <Alert status={err ? 'warning' : 'success'}>
      <Alert.Indicator />
      <Alert.Content className="min-w-0">
        <Alert.Title>执行完成：成功 {n('done')} 项，跳过 {n('skipped')} 项{err ? '，失败 ' + err + ' 项' : ''}</Alert.Title>
        <Alert.Description>
          <ul className="mt-2 flex max-h-64 flex-col gap-1.5 overflow-y-auto">
            {items.map((it, i) => {
              const st = STATUS[it.status] ?? { label: it.status, color: 'default' as const }
              return (
                <li key={i} className="flex items-start gap-2 text-xs">
                  <Chip size="sm" variant="soft" color={st.color} className="shrink-0">{st.label}</Chip>
                  <span className="min-w-0">
                    <span className="font-mono">{it.task_code}</span>
                    {it.message && <span className="text-muted"> — {it.message}</span>}
                  </span>
                </li>
              )
            })}
          </ul>
        </Alert.Description>
      </Alert.Content>
      <CloseButton aria-label="收起结果" onPress={onDismiss} />
    </Alert>
  )
}

// internal/panel/frontend/src/components/TasksModal.svelte
<script>
  import { api } from '../lib/api.js';
  import { ui, toast, authFailed } from '../lib/stores.svelte.js';
  import Modal from './Modal.svelte';

  // 可自动完成的任务（与后端 autoActions 表一致）：判据为行为事件、可经网关复现。
  // 其余任务需在官方客户端内交互，面板只展示指引（行 title 提示）。
  const AUTO_TASKS = {
    chat_5: '上报 5 条对话活跃事件（自动补足差额）',
    first_buddy: '上报解锁 → 同意协议 → 领取第一只 Buddy',
    'Model_chat_GLM5.2': '接受任务 → glm-5.2 真实对话一次 → 对齐模型上报',
    RichMeow_Chat: '桌面指纹事件链上报（已验证可点亮）',
    Buddy_App: '上报「进入 Buddy 应用」事件链（已验证可点亮）',
    Buddy_App_QQ: '上报「进入企鹅教师助手」事件链（已验证可点亮）',
    automation_1: '上报「定时任务创建」事件（已验证可点亮）',
    Library_read: '上报「读资料库介绍」事件（已验证可点亮）',
    template_5: '上报「使用模板创建任务」事件组 ×5（三账号实测点亮）',
    playbook_prompt: '上报「灵感案例做同款发送 Prompt」事件组（三账号实测点亮）',
    create_canvas: '上报「设计创意画布创建」事件组（三账号实测点亮，+300 分）',
    expert_5: '真实专家召唤+使用链 ×5（专家市场+真实 chat，三账号实测点亮）',
    Expert_team_use_3: '真实专家团召唤+使用链 ×3（三账号实测点亮）',
    Hp_Appearance: '设置主题 API + 皮肤生效事件（两账号实测点亮）',
    black_cat: '夜猫子：23:00–08:00 窗口内 glm-5.2 对话补足（窗口外提示等 23 点排程）',
    Expert_lighthouse: '真实轻量云专家召唤+使用链（真实对话 requestId，两账号实测点亮）',
    skill_1: '真实对话 + skill_info 技能加载事件（实测点亮）',
    school_season: '校园日（小程序口径）：accept → mini 对话+activityId 上报 → 领奖（+100c+5e）',
    Sequential_Tasks_1: '小程序首对话（小程序口径）：accept → mini 对话上报 → 领奖（+100c+5e）'
  };

  let tasks = $state([]);
  let state = $state('loading'); // loading | ready | empty | error
  let stateMsg = $state('');
  let busy = $state(false);

  async function load() {
    const uid = ui.taskUid;
    if (!uid) return;
    state = 'loading';
    tasks = [];
    try {
      const d = await api('accounts/' + encodeURIComponent(uid) + '/tasks');
      const list = d.tasks || [];
      if (!list.length) {
        state = 'empty';
        return;
      }
      // 有进度或可领取的排前面，已领取沉底——一眼看到"现在该做什么"。
      list.sort(
        (a, b) => a.claimed - b.claimed || b.claimable - a.claimable || String(a.task_code).localeCompare(String(b.task_code))
      );
      tasks = list;
      state = 'ready';
    } catch (e) {
      if (e.unauthorized) authFailed();
      state = 'error';
      stateMsg = e.message;
    }
  }

  function rewardOf(t) {
    const parts = [];
    if (t.credit) parts.push('+' + t.credit + ' 分');
    if (t.energy) parts.push('+' + t.energy + ' 能');
    if (t.reward_buddy) parts.push('Buddy');
    return parts.length ? parts.join(' ') : '—';
  }

  function tipOf(t) {
    return [t.title, t.task_desc || t.description, t.jump_url ? '跳转：' + t.jump_url : ''].filter(Boolean).join('\n');
  }

  async function act(kind, code, btn) {
    const uid = ui.taskUid;
    if (!uid || busy) return;
    busy = true;
    try {
      if (kind === 'auto') {
        const r = await api('accounts/' + encodeURIComponent(uid) + '/tasks/auto', {
          method: 'POST',
          body: { task_code: code }
        });
        if (r.skipped) {
          toast(r.message || '已跳过', 'ok');
        } else {
          const advanced = r.progress_before !== r.progress_after;
          let m = r.message || '已执行';
          if (r.progress_after) m += `（进度 ${r.progress_before} → ${r.progress_after}）`;
          if (r.claimed) m += '，奖励已自动到账';
          else if (r.claimable) m += r.claim_error ? '，可点「领取」重试' : '';
          else if (r.attempt && !advanced) m += '；进度未动，该任务可能需要官方客户端';
          toast(m, r.claimed || advanced ? 'ok' : 'err');
        }
        dispatchEvent(new CustomEvent('wb:refresh'));
      } else {
        const path = 'accounts/' + encodeURIComponent(uid) + '/tasks/' + (kind === 'claim' ? 'claim' : 'accept');
        const body = kind === 'claim' ? { task_code: code } : { task_codes: [code] };
        await api(path, { method: 'POST', body });
        toast(kind === 'claim' ? '已领取奖励' : '已接受任务', 'ok');
        if (kind === 'claim') dispatchEvent(new CustomEvent('wb:refresh'));
      }
    } catch (e) {
      if (e.unauthorized) authFailed();
      else toast(e.message, 'err');
    } finally {
      busy = false;
      load();
    }
  }

  async function acceptAll() {
    const uid = ui.taskUid;
    if (!uid || busy) return;
    busy = true;
    try {
      const r = await api('accounts/' + encodeURIComponent(uid) + '/tasks/accept_all', { method: 'POST' });
      const n = r.accepted || 0;
      if (r.failed && r.failed.length) toast(`已接受 ${n} 个，${r.failed.length} 个被上游拒绝（可重试）`, 'err');
      else toast(n ? `已接受 ${n} 个任务` : r.message || '所有任务均已接受', 'ok');
    } catch (e) {
      if (e.unauthorized) authFailed();
      else toast(e.message, 'err');
    } finally {
      busy = false;
      load();
    }
  }

  async function autoAll() {
    const uid = ui.taskUid;
    if (!uid || busy) return;
    if (!confirm('将依次执行：补报对话事件、领取 Buddy、glm-5.2 对话、尝试上报。\n过程约 1-2 分钟（含真实对话），确认继续？')) return;
    busy = true;
    try {
      const r = await api('accounts/' + encodeURIComponent(uid) + '/tasks/auto_all', { method: 'POST' });
      const okN = (r.results || []).filter((x) => x.status === 'done').length;
      const skipN = (r.results || []).filter((x) => x.status === 'skipped').length;
      const errN = (r.results || []).filter((x) => x.status === 'error').length;
      toast(`执行完成：成功 ${okN} 项，跳过 ${skipN} 项${errN ? '，失败 ' + errN + ' 项' : ''}`, errN ? 'err' : 'ok');
    } catch (e) {
      if (e.unauthorized) authFailed();
      else toast(e.message, 'err');
    } finally {
      busy = false;
      load();
    }
  }

  $effect(() => {
    if (ui.taskUid) load();
    else {
      tasks = [];
      state = 'loading';
    }
  });
</script>

<Modal
  open={ui.taskUid !== null}
  title="积分任务"
  hint={ui.taskUid ? String(ui.taskUid).slice(0, 16) : ''}
  wide={true}
  onclose={() => {
    ui.taskUid = null;
  }}
>
  {#if state === 'loading'}
    <div class="state"><span class="dots">查询中</span></div>
  {:else if state === 'empty'}
    <div class="state">该账号暂无任务</div>
  {:else if state === 'error'}
    <div class="state err">{stateMsg}</div>
  {:else}
    <div class="tbl-wrap">
      <table class="acc md">
        <thead>
          <tr>
            <th>任务</th>
            <th>进度</th>
            <th>奖励</th>
            <th>状态</th>
            <th class="c-acts"></th>
          </tr>
        </thead>
        <tbody>
          {#each tasks as t (t.task_code)}
            {@const cur = t.current ?? 0}
            {@const tgt = t.target ?? 0}
            {@const prog = tgt ? cur + ' / ' + tgt : tgt === 0 && cur > 0 ? String(cur) : '—'}
            <tr title={tipOf(t)}>
              <td class="who">
                <div class="nm">{t.title || t.task_code}</div>
                <div class="id">{t.task_code}{t.tag ? ' · ' + t.tag : ''}</div>
              </td>
              <td class="num">{prog}</td>
              <td class="num">{rewardOf(t)}</td>
              <td>
                {#if t.claimed}<span class="tag ok">已领取</span>
                {:else if t.claimable}<span class="tag warn">可领取</span>
                {:else if t.locked}<span class="tag mute">未解锁</span>
                {:else if t.accept_status === 'accepted'}<span class="tag mute">进行中</span>
                {:else}<span class="tag mute">未接受</span>{/if}
              </td>
              <td class="acts">
                {#if !t.claimed && !t.locked}
                  {#if t.claimable}
                    <button class="btn xs primary" disabled={busy} onclick={(e) => act('claim', t.task_code, e.currentTarget)}>领取</button>
                  {:else if AUTO_TASKS[t.task_code]}
                    <button
                      class="btn xs primary"
                      disabled={busy}
                      title={AUTO_TASKS[t.task_code]}
                      onclick={(e) => act('auto', t.task_code, e.currentTarget)}>一键完成</button
                    >
                  {:else if t.accept_status !== 'accepted'}
                    <button class="btn xs" disabled={busy} onclick={(e) => act('accept', t.task_code, e.currentTarget)}>接受</button>
                  {/if}
                {/if}
              </td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
  {/if}
  {#snippet footer()}
    <span class="grow"></span>
    <button class="btn" disabled={busy} onclick={acceptAll}>全部接受</button>
    <button class="btn primary" disabled={busy} onclick={autoAll}>一键完成可自动任务</button>
    <button class="btn" onclick={load}>重新查询</button>
    <button
      class="btn"
      onclick={() => {
        ui.taskUid = null;
      }}>关闭</button
    >
  {/snippet}
</Modal>
