// internal/panel/frontend/src/components/KeyGate.svelte
<script>
  import { api, setKey } from '../lib/api.js';
  import { ui, toast } from '../lib/stores.svelte.js';
  import Modal from './Modal.svelte';

  let val = $state('');
  let bad = $state(false);
  let busy = $state(false);

  async function enter() {
    const v = val.trim();
    if (!v || busy) return;
    busy = true;
    setKey(v);
    try {
      await api('overview');
      bad = false;
      ui.keyOpen = false;
      val = '';
      dispatchEvent(new CustomEvent('wb:refresh'));
    } catch {
      bad = true;
    } finally {
      busy = false;
    }
  }
</script>

<Modal open={ui.keyOpen} title="需要访问密钥" hint="该网关已启用 api_key 鉴权，请输入 config.json 中的密钥。" onclose={() => {}}>
  <input
    type="password"
    class="fld-input"
    placeholder="api_key"
    autocomplete="current-password"
    bind:value={val}
    onkeydown={(e) => {
      if (e.key === 'Enter') enter();
    }}
  />
  {#if bad}
    <div class="state err mt-2.5">密钥不正确，请重试。</div>
  {/if}
  {#snippet footer()}
    <span class="grow"></span>
    <button class="btn primary" onclick={enter} disabled={busy}>进入</button>
  {/snippet}
</Modal>

// web/src/components/KeyGate.tsx
import { useEffect, useState } from 'react'
import { FieldError, Form, Input, Label, Modal, TextField } from '@heroui/react'
import { useQueryClient } from '@tanstack/react-query'
import { AUTH_EVENT, api, setKey } from '../lib/api'
import { BusyButton } from './Feedback'

/** 网关开了 api_key 鉴权时，任一接口返回 401 就弹出这个框；输对之前不能关闭 */
export function KeyGate() {
  const qc = useQueryClient()
  const [open, setOpen] = useState(false)
  const [value, setValue] = useState('')
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)

  useEffect(() => {
    const on = () => setOpen(true)
    window.addEventListener(AUTH_EVENT, on)
    return () => window.removeEventListener(AUTH_EVENT, on)
  }, [])

  const submit = async () => {
    const k = value.trim()
    if (!k) return
    setKey(k)
    setBusy(true)
    try {
      await api('overview')
      setError('')
      setOpen(false)
      await qc.invalidateQueries()
    } catch {
      setError('密钥不正确，请重试。')
    } finally {
      setBusy(false)
    }
  }

  return (
    <Modal.Backdrop isOpen={open} isDismissable={false} isKeyboardDismissDisabled>
      <Modal.Container size="sm">
        <Modal.Dialog>
          <Modal.Header>
            <Modal.Heading>需要访问密钥</Modal.Heading>
            <p className="mt-1.5 text-sm text-muted">该网关已启用 api_key 鉴权，请输入 config.json 中的密钥。</p>
          </Modal.Header>
          <Form className="contents" onSubmit={(e) => { e.preventDefault(); void submit() }}>
            <Modal.Body>
              <TextField autoFocus isInvalid={!!error} value={value} onChange={setValue} type="password" name="api_key">
                <Label>api_key</Label>
                <Input autoComplete="current-password" />
                <FieldError>{error}</FieldError>
              </TextField>
            </Modal.Body>
            <Modal.Footer>
              <BusyButton type="submit" busy={busy} isDisabled={!value.trim()}>进入</BusyButton>
            </Modal.Footer>
          </Form>
        </Modal.Dialog>
      </Modal.Container>
    </Modal.Backdrop>
  )
}
